### ISSUE TITLE
Explore OPA data (and other data sets) for assessment model

### ISSUE THREAD

**Issue by mjumbewu** [musa-509-spring-2023/philly-mass-appraisals-1#6]
**Acceptance Criteria:**
- A markdown document explaining the useful fields and an outline of the feature engineering necessary for model training and prediction
- Any artifacts (notebooks, R markdown, etc) should be committed to the `eda/` folder. Data sources for the exploration should be documented, but the data itself should not be committed to the repository.

**Comment by lizard12995** [comment]
We created a pull request for this issue but I don't know how to link it!

**Comment by mjumbewu** [comment]
The exploration looks done!
